import javax.swing.*;
import java.awt.*;

public class FriendForm {
    private JPanel mainPanel;
    private JPanel friendPanel;
    private JLabel friendNameLabel;
    private JLabel friendLastMusic;

    public FriendForm(String name, String lastMusic) {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
        friendNameLabel.setText(name);
        friendLastMusic.setText(lastMusic);
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public void changeLastMusic(String lastMusic) {
        friendLastMusic.setText(lastMusic);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBackground(new Color(-15592942));
        mainPanel.setForeground(new Color(-855310));
        friendPanel = new JPanel();
        friendPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        friendPanel.setBackground(new Color(-15592942));
        friendPanel.setForeground(new Color(-855310));
        mainPanel.add(friendPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(200, 60), new Dimension(200, 60), new Dimension(200, 60), 0, false));
        friendNameLabel = new JLabel();
        friendNameLabel.setBackground(new Color(-15592942));
        friendNameLabel.setForeground(new Color(-855310));
        friendNameLabel.setText("name");
        friendPanel.add(friendNameLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        friendLastMusic = new JLabel();
        friendLastMusic.setBackground(new Color(-15592942));
        friendLastMusic.setForeground(new Color(-7283726));
        friendLastMusic.setText("onliene");
        friendPanel.add(friendLastMusic, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
