import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class PlayListForm {
    private JPanel mainPanel;
    private JButton addIcon;
    private JButton renameIcon;
    private JButton optionButton;
    private JButton nameButton;
    private GUI app;
    private PlayList playList;

    public PlayListForm(GUI app, PlayList playList) {
        this.app = app;
        this.playList = playList;
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();

    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JButton getAddIcon() {
        return addIcon;
    }

    public JButton getNameButton() {
        return nameButton;
    }

    public JButton getRenameIcon() {
        return renameIcon;
    }

    public JButton getOptionButton() {
        return optionButton;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBackground(new Color(-15592942));
        mainPanel.setForeground(new Color(-855310));
        mainPanel.setMaximumSize(new Dimension(200, 40));
        mainPanel.setMinimumSize(new Dimension(200, 40));
        mainPanel.setPreferredSize(new Dimension(200, 40));
        optionButton = new JButton();
        optionButton.setBackground(new Color(-15592942));
        optionButton.setBorderPainted(false);
        optionButton.setContentAreaFilled(false);
        optionButton.setFocusPainted(false);
        optionButton.setForeground(new Color(-855310));
        optionButton.setIcon(new ImageIcon(getClass().getResource("/Logo/option-white.png")));
        optionButton.setText("");
        mainPanel.add(optionButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(30, 40), new Dimension(30, 40), new Dimension(30, 40), 0, false));
        nameButton = new JButton();
        nameButton.setBackground(new Color(-15592942));
        nameButton.setBorderPainted(false);
        nameButton.setContentAreaFilled(false);
        nameButton.setFocusPainted(false);
        nameButton.setForeground(new Color(-1));
        nameButton.setText("Name");
        mainPanel.add(nameButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
