import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;

public class PlayingMusicForm {
    private JPanel mainPanel;
    private JLabel imagePanel;
    private JLabel nameLabel;
    private JLabel artistLabel;
    private Music music;

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public PlayingMusicForm(Music music) {



// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();



        try {
            this.music = music;
            System.out.println(music.getTitle());
            String name = music.getTitle();
            nameLabel.setText(name);
            artistLabel.setText(music.getArtist());
            BufferedImage img = ImageIO.read(new ByteArrayInputStream(music.getImageData()));
            BufferedImage resizedImg = new BufferedImage(50, 50, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2 = resizedImg.createGraphics();
            g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
            g2.drawImage(img, 0, 0, 50, 50, null);
            g2.dispose();
            imagePanel.setIcon(new ImageIcon(resizedImg));
            imagePanel.revalidate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBackground(new Color(-14145496));
        imagePanel = new JLabel();
        imagePanel.setBackground(new Color(-14145496));
        imagePanel.setText("");
        mainPanel.add(imagePanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(60, 60), new Dimension(60, 60), new Dimension(60, 60), 0, false));
        nameLabel = new JLabel();
        nameLabel.setForeground(new Color(-855310));
        nameLabel.setText("");
        mainPanel.add(nameLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(60, 30), new Dimension(60, 30), new Dimension(60, 30), 0, false));
        artistLabel = new JLabel();
        artistLabel.setBackground(new Color(-14145496));
        artistLabel.setForeground(new Color(-855310));
        artistLabel.setText("");
        mainPanel.add(artistLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(60, 30), new Dimension(60, 30), new Dimension(60, 30), 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
