import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.io.PrintWriter;

public class RequestForm {
    private JPanel mainPanel;
    private JButton yesButton;
    private JButton noButton;
    private JLabel requestLabel;
    private JPanel panel1;
    private JFrame frame;
    private PrintWriter setOutTheRequest;
    private Owner owner;
    private String requestedName;
    private String requestedIP;
    private String requestedID;

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JButton getYesButton() {
        return yesButton;
    }

    public JButton getNoButton() {
        return noButton;
    }

    public JLabel getRequestLabel() {
        return requestLabel;
    }

    public RequestForm(JFrame frame, PrintWriter setOutTheRequest, Owner owner, String requestedName, String requestedIP, String requestedID) {
        this.frame = frame;
        this.setOutTheRequest = setOutTheRequest;
        this.owner = owner;
        this.requestedID = requestedID;
        this.requestedIP = requestedIP;
        this.requestedName = requestedName;

// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
        noButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                setOutTheRequest.println("no");
                setOutTheRequest.close();
                frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
            }
        });
        yesButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                owner.accept(Integer.parseInt(requestedID), requestedName, requestedIP);
                setOutTheRequest.println("ok");
                setOutTheRequest.close();
                frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-15592942));
        panel1.setForeground(new Color(-855310));
        mainPanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(300, 100), new Dimension(300, 100), new Dimension(300, 100), 0, false));
        requestLabel = new JLabel();
        requestLabel.setBackground(new Color(-15592942));
        requestLabel.setForeground(new Color(-855310));
        requestLabel.setText("");
        panel1.add(requestLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(300, 50), new Dimension(300, 50), new Dimension(300, 50), 0, false));
        yesButton = new JButton();
        yesButton.setBackground(new Color(-15592942));
        yesButton.setBorderPainted(false);
        yesButton.setFocusPainted(false);
        yesButton.setForeground(new Color(-855310));
        yesButton.setText("Yes");
        panel1.add(yesButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 50), new Dimension(150, 50), new Dimension(150, 50), 0, false));
        noButton = new JButton();
        noButton.setBackground(new Color(-15592942));
        noButton.setBorderPainted(false);
        noButton.setFocusPainted(false);
        noButton.setForeground(new Color(-855310));
        noButton.setText("No");
        panel1.add(noButton, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 50), new Dimension(150, 50), new Dimension(150, 50), 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
